-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Trash.Object.SiteStatsNode exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Trash.Object
import Trash.Interface
import Trash.Union
import Trash.Scalar
import Trash.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Trash.Object.SiteStatsNode
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field Trash.Scalar.Id Trash.Object.SiteStatsNode
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Trash.Scalar.Id)


{-| 
-}
volumePerPersonPerWeek : Field Float Trash.Object.SiteStatsNode
volumePerPersonPerWeek =
      Object.fieldDecoder "VolumePerPersonPerWeek" [] (Decode.float)


{-| 
-}
volumeStandardDeviation : Field Float Trash.Object.SiteStatsNode
volumeStandardDeviation =
      Object.fieldDecoder "VolumeStandardDeviation" [] (Decode.float)


litresPerPersonPerWeek : Field Float Trash.Object.SiteStatsNode
litresPerPersonPerWeek =
      Object.fieldDecoder "litresPerPersonPerWeek" [] (Decode.float)


litresStandardDeviation : Field Float Trash.Object.SiteStatsNode
litresStandardDeviation =
      Object.fieldDecoder "litresStandardDeviation" [] (Decode.float)


gallonsPerPersonPerWeek : Field Float Trash.Object.SiteStatsNode
gallonsPerPersonPerWeek =
      Object.fieldDecoder "gallonsPerPersonPerWeek" [] (Decode.float)


gallonsStandardDeviation : Field Float Trash.Object.SiteStatsNode
gallonsStandardDeviation =
      Object.fieldDecoder "gallonsStandardDeviation" [] (Decode.float)
