-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Trash.Object.StatsNode exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Trash.Object
import Trash.Interface
import Trash.Union
import Trash.Scalar
import Trash.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Trash.Object.StatsNode
selection constructor =
    Object.selection constructor
site : SelectionSet decodesTo Trash.Object.SiteStatsNode -> Field decodesTo Trash.Object.StatsNode
site object_ =
      Object.selectionField "site" [] (object_) (identity)


user : SelectionSet decodesTo Trash.Object.UserStatsNode -> Field decodesTo Trash.Object.StatsNode
user object_ =
      Object.selectionField "user" [] (object_) (identity)
