-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Trash.Object.TrashNode exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Object as Object
import Graphql.SelectionSet exposing (SelectionSet)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Trash.Object
import Trash.Interface
import Trash.Union
import Trash.Scalar
import Trash.InputObject
import Json.Decode as Decode
import Graphql.Internal.Encode as Encode exposing (Value)



{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Trash.Object.TrashNode
selection constructor =
    Object.selection constructor
{-| 
-}
id : Field Trash.Scalar.Id Trash.Object.TrashNode
id =
      Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Trash.Scalar.Id)


{-| 
-}
volume : Field Float Trash.Object.TrashNode
volume =
      Object.fieldDecoder "Volume" [] (Decode.float)


{-| 
-}
date : Field Trash.Scalar.Date Trash.Object.TrashNode
date =
      Object.fieldDecoder "date" [] (Object.scalarDecoder |> Decode.map Trash.Scalar.Date)


litres : Field Float Trash.Object.TrashNode
litres =
      Object.fieldDecoder "litres" [] (Decode.float)


gallons : Field Float Trash.Object.TrashNode
gallons =
      Object.fieldDecoder "gallons" [] (Decode.float)
