-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Trash.Mutation exposing (..)

import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Trash.Enum.Metric
import Trash.InputObject
import Trash.Interface
import Trash.Object
import Trash.Scalar
import Trash.Union


{-| Select fields to build up a top-level mutation. The request can be sent with
functions from `Graphqelm.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootMutation
selection constructor =
    Object.selection constructor


type alias SaveTrashOptionalArguments =
    { volume : OptionalArgument Float, metric : OptionalArgument Trash.Enum.Metric.Metric }


type alias SaveTrashRequiredArguments =
    { token : String, date : Trash.Scalar.Date }


saveTrash : (SaveTrashOptionalArguments -> SaveTrashOptionalArguments) -> SaveTrashRequiredArguments -> SelectionSet decodesTo Trash.Object.SaveTrash -> Field (Maybe decodesTo) RootMutation
saveTrash fillInOptionals requiredArgs object =
    let
        filledInOptionals =
            fillInOptionals { volume = Absent, metric = Absent }

        optionalArgs =
            [ Argument.optional "volume" filledInOptionals.volume Encode.float, Argument.optional "metric" filledInOptionals.metric (Encode.enum Trash.Enum.Metric.toString) ]
                |> List.filterMap identity
    in
    Object.selectionField "saveTrash" (optionalArgs ++ [ Argument.required "token" requiredArgs.token Encode.string, Argument.required "date" requiredArgs.date (\(Trash.Scalar.Date raw) -> Encode.string raw) ]) object (identity >> Decode.nullable)
