-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Trash.Object exposing (..)


type SaveTrash
    = SaveTrash


type SiteStatsNode
    = SiteStatsNode


type StatsNode
    = StatsNode


type TrashNode
    = TrashNode


type UserStatsNode
    = UserStatsNode
