-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Trash.Object exposing (..)


type SaveTrash
    = SaveTrash


type SiteStatsNode
    = SiteStatsNode


type StatsNode
    = StatsNode


type TrashNode
    = TrashNode


type UserStatsNode
    = UserStatsNode
