-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Trash.Object exposing (..)


type SaveTrash
    = SaveTrash


type TrashNode
    = TrashNode
