-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Trash.Scalar exposing (..)


type Date
    = Date String


type Id
    = Id String
