-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Trash.Scalar exposing (..)


type Date
    = Date String


type Id
    = Id String
