-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql
module Trash.Enum.Metric exposing (..)

import Json.Decode as Decode exposing (Decoder)


type Metric
    = Gallons
    | Litres
decoder : Decoder Metric
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "Gallons" ->
                        Decode.succeed Gallons

                    "Litres" ->
                        Decode.succeed Litres

                    _ ->
                        Decode.fail ("Invalid Metric type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
        )
        

{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Metric -> String
toString enum =
    case enum of
        Gallons ->
                "Gallons"


        Litres ->
                "Litres"
